project:
  type: website
  output-dir: docs

website:
  title: "신록예찬's Blog"
  
  page-footer:
    border: true
    
format:
  html:
    theme: cosmo
    number-sections: true
    css: styles.css
    toc: true
    toc-location: right
    highlight-style: github
    toc-depth: 2  
  